# Generated by Django 4.2.9 on 2024-04-27 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("charts_of_account", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Journal",
            fields=[
                (
                    "journal_num",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("journal_date", models.DateField()),
                ("desc", models.TextField(null=True)),
                ("credit_sum", models.IntegerField(null=True)),
                ("debit_sum", models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trans_type",
                    models.CharField(
                        choices=[("KRD", "Kredit"), ("DBT", "Debit")], max_length=3
                    ),
                ),
                ("value", models.IntegerField(null=True)),
                (
                    "acc_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="charts_of_account.chartsofaccount",
                    ),
                ),
                (
                    "journal_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="journal.journal",
                    ),
                ),
            ],
        ),
    ]
